services:
  Macopedia\Translator\Translator\GoogleTranslator:
    arguments:
      - '@Google\Cloud\Translate\V2\TranslateClient'

  Google\Cloud\Translate\V2\TranslateClient:
    arguments:
      - { key: '%env(GOOGLE_API_KEY)%' }
