services:
  Piotrmus\Translator\Translator\GoogleTranslator:
    arguments:
      - '@Google\Cloud\Translate\V2\TranslateClient'

  Piotrmus\Translator\Connector\Processor\MassEdit\TranslateAttributesProcessor:
    arguments:
      - '@Piotrmus\Translator\Translator\GoogleTranslator'

  Google\Cloud\Translate\V2\TranslateClient:
    arguments:
      - { apiKey: '%env(GOOGLE_API_KEY)%' }

  piotrmus.job.update_product_translations:
    class: Akeneo\Tool\Component\Batch\Job\Job
    arguments:
      - 'update_product_translations'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - [ '@piotrmus.step.update_product_translations.mass_edit' ]
    tags:
      - { name: akeneo_batch.job, connector: '%pim_enrich.connector_name.mass_edit%', type: '%pim_enrich.job.mass_edit_type%' }

  piotrmus.job.default_values_provider.translate_product:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\DefaultValueProvider\ProductMassEdit
    arguments:
      - [ 'update_product_translations' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }

  piotrmus.job.constraint_collection_provider.translate_product:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductMassEdit
    arguments:
      - [ 'update_product_translations' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

  piotrmus.step.update_product_translations.mass_edit:
    class: Akeneo\Tool\Component\Batch\Step\ItemStep
    arguments:
      - 'perform'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_enrich.reader.database.products_and_variant_products_of_product_models'
      - '@Piotrmus\Translator\Connector\Processor\MassEdit\TranslateAttributesProcessor'
      - '@pim_connector.writer.database.product'
      - 10