services:
  macopedia.step.update_product_translations.mass_edit:
    class: '%pim_connector.step.item_step.class%'
    arguments:
      - 'perform'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_enrich.reader.database.product_and_product_model'
      - '@Macopedia\Translator\Connector\Processor\MassEdit\TranslateAttributesProcessor'
      - '@pim_enrich.writer.database.product_and_product_model_writer'
      - '%pim_job_product_batch_size%'
