extensions:
  piotrmus-mass-product-edit-translate-attributes:
    module: piotrmus-translator/mass-edit/translate
    parent: pim-mass-product-edit
    position: 500
    config:
      title: pim_enrich.mass_edit.product.title
      label: piotrmus.mass_edit.attribute_translator.label
      labelCount: piotrmus.mass_edit.attribute_translator.label_count
      description: piotrmus.mass_edit.attribute_translator.description
      code: update_product_translations
      jobInstanceCode: update_product_translations
      icon: icon-compare